// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/messages": {
            "get": {
                "description": "Get sending messages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Sending Messages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/message.SendingMessage"
                            }
                        }
                    }
                }
            }
        },
        "/api/worker/start": {
            "post": {
                "description": "Start worker with redis channel",
                "tags": [
                    "Worker"
                ],
                "summary": "Start worker",
                "responses": {}
            }
        },
        "/api/worker/stop": {
            "post": {
                "description": "Stop worker with redis channel",
                "tags": [
                    "Worker"
                ],
                "summary": "Stop worker",
                "responses": {}
            }
        }
    },
    "definitions": {
        "message.SendingMessage": {
            "type": "object",
            "properties": {
                "messageId": {
                    "type": "string"
                },
                "sentAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Insider Messaging API",
	Description:      "Automatic Sending Message Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
